# Generated by Django 2.0.3 on 2018-03-11 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0002_predictions'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictions',
            name='Winner',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='predictions',
            name='First_pokemon',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='predictions',
            name='Second_pokemon',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
